load (":ruby_sources_versions.bzl", "run_ruby_gemver", "run_ruby_binver")
load (":gems_check_gemfile.bzl", "check_gems_gemfile")

run_ruby_gemver (
  name = "ruby_gem_ver"
)

run_ruby_binver(
  name = "ruby_bin_ver"
)

check_gems_gemfile(
  name = "check_gem_gemfile"
)